### ISSUE TITLE
Error when running vendor.py script

### ISSUE THREAD

**Issue by tunghoang290780** [pulp-platform/register_interface#13]
Hi,

I clone a clean repo and checkout commit 05dc97f (Release v0.2.2)

Then I run the below command
./util/vendor.py vendor/lowrisc_opentitan.vendor.hjson --update

And I have the following errors which I suppose due to the mismatching between register_interface and opentitan upstream repo  
![image](https://user-images.githubusercontent.com/53881329/115453972-18233a80-a1d5-11eb-8953-9abdcd0515be.png)

Could you give some hints to resolve this issue?

Many thanks
/T

**Comment by zarubaf** [comment]
Is there a specific reason you are running the `./util/vendor.py vendor/lowrisc_opentitan.vendor.hjson --update`? The files are already in the repository and you only would need to update it in case you are missing a feature/bug fix from upstream (e.g., OpenTitan). 99% of the time that would be the maintainer of this repository who will take care of that :-)

That might be a bit misleading in the README I must admit.
